import { useState, useRef, useEffect } from 'react';
import {
  MessageCircle, X, Send, Globe, CheckSquare, Square,
  Clock, MapPin, Copy, Bell, BellRing, Check, Sparkles, ChevronDown, ChevronUp, AlertCircle
} from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { getSubjectAttendance, getFeeRecord, getExamsForDepartment, getMarks } from '@/data/mockData';
import { analyzeTomorrowTimetable, type DayAnalysis, type ChecklistItem } from '@/utils/timetableReminder';

interface ChatMessage {
  id: string;
  role: 'user' | 'bot';
  text: string;
  type?: 'text' | 'timetable_reminder';
  analysis?: DayAnalysis;
}

export default function AIChatbot() {
  const [open, setOpen] = useState(false);
  const [showPill, setShowPill] = useState(true);
  const [input, setInput] = useState('');
  const [lang, setLang] = useState<'en' | 'ta'>('en');
  const [dailyAlert, setDailyAlert] = useState(true);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [expandedPeriods, setExpandedPeriods] = useState<Record<string, boolean>>({});

  const { currentStudent } = useApp();
  const messagesEnd = useRef<HTMLDivElement>(null);

  // Initialize with greeting & timetable reminder proactive trigger
  const [messages, setMessages] = useState<ChatMessage[]>(() => {
    return [
      {
        id: 'init-1',
        role: 'bot',
        text: 'Hello! I\'m your AI Smart Assistant. I can analyze tomorrow\'s periods, prepare your bag packing checklist, check attendance, exams, and more!',
      },
    ];
  });

  useEffect(() => {
    messagesEnd.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, open]);

  // Handle toggling packing checklist item
  const toggleItemPacked = (msgId: string, itemId: string) => {
    setMessages(prev => prev.map(msg => {
      if (msg.id !== msgId || !msg.analysis) return msg;
      const updatedList = msg.analysis.checklist.map(item =>
        item.id === itemId ? { ...item, packed: !item.packed } : item
      );
      return {
        ...msg,
        analysis: {
          ...msg.analysis,
          checklist: updatedList,
        },
      };
    }));
  };

  // Copy checklist to clipboard
  const handleCopyChecklist = (msgId: string, analysis: DayAnalysis) => {
    const lines = [
      `🎒 Tomorrow's Packing Checklist (${analysis.targetDay}, ${analysis.dateStr})`,
      `📅 ${analysis.slots.length} Periods Scheduled:`,
      ...analysis.slots.map(s => `  • P${s.period} (${s.time}): ${s.subjectName} @ ${s.room}`),
      '',
      '✅ Items to Pack:',
      ...analysis.checklist.map(item => `  [${item.packed ? '✔' : ' '}] ${item.icon} ${item.item} (${item.reason})`),
      '',
      '— Generated by Bharath Institute AI Assistant',
    ];
    navigator.clipboard.writeText(lines.join('\n'));
    setCopiedId(msgId);
    setTimeout(() => setCopiedId(null), 2500);
  };

  const getAnalysis = () => {
    return analyzeTomorrowTimetable(
      currentStudent?.department || 'CSE',
      currentStudent?.year || 3,
      currentStudent?.section || 'A'
    );
  };

  function isReminderQuery(q: string): boolean {
    const terms = [
      'tomorrow', 'naliku', 'naalaiki', 'period', 'periods', 'timetable',
      'time table', 'remainder', 'reminder', 'checklist', 'pack', 'packing',
      'bag', 'what to bring', 'bring', 'lab', 'schedule', 'classes'
    ];
    return terms.some(term => q.includes(term));
  }

  function handleSendQuery(customQuery?: string) {
    const qText = (customQuery !== undefined ? customQuery : input).trim();
    if (!qText) return;

    const q = qText.toLowerCase();
    const userMsgId = `user-${Date.now()}`;
    const botMsgId = `bot-${Date.now() + 1}`;

    const userMsg: ChatMessage = { id: userMsgId, role: 'user', text: qText };

    if (!currentStudent) {
      const botMsg: ChatMessage = {
        id: botMsgId,
        role: 'bot',
        text: lang === 'en' ? 'No student data available.' : 'மாணவர் தரவு கிடைக்கவில்லை.',
      };
      setMessages(prev => [...prev, userMsg, botMsg]);
      setInput('');
      return;
    }

    // Check if user is asking about tomorrow's timetable/periods/packing checklist
    if (isReminderQuery(q)) {
      const analysis = getAnalysis();
      const introText = lang === 'en'
        ? `🎒 Here is your schedule analysis for tomorrow (${analysis.targetDay}, ${analysis.dateStr}). You have ${analysis.slots.length} periods scheduled${analysis.hasLab ? ` including Lab sessions in ${analysis.labRooms.join(', ')}` : ''}.\n\nI have generated your customized bag packing checklist below. Mark items as you pack!`
        : `🎒 நாளைக்கான (${analysis.targetDayTa}) வகுப்பு அட்டவணை பகுப்பாய்வு செய்யப்பட்டது. நாளை ${analysis.slots.length} வகுப்புகள் திட்டமிடப்பட்டுள்ளன${analysis.hasLab ? ` (${analysis.labRooms.join(', ')}-ல் செய்முறை வகுப்புகள் உட்பட)` : ''}.\n\nநீங்கள் எடுத்துச் செல்ல வேண்டிய பொருட்களின் பட்டியல் கீழே உள்ளது:`;

      const botMsg: ChatMessage = {
        id: botMsgId,
        role: 'bot',
        text: introText,
        type: 'timetable_reminder',
        analysis,
      };

      setMessages(prev => [...prev, userMsg, botMsg]);
      setInput('');
      return;
    }

    // Attendance
    if (q.includes('attendance')) {
      const subjects = getSubjectAttendance(currentStudent.id);
      const subjectLines = subjects.map(s =>
        `  • ${s.subjectName}: ${s.percentage}% (${s.attended}/${s.totalClasses})`
      ).join('\n');
      const riskWarning = currentStudent.overallAttendance < 75
        ? (lang === 'en'
          ? '\n\n⚠️ Warning: Your attendance is below 75%. You may face shortage issues. Please attend classes regularly.'
          : '\n\n⚠️ எச்சரிக்கை: உங்கள் வருகை 75%க்கு கீழ் உள்ளது. தொடர்ந்து வகுப்புகளில் கலந்துகொள்ளவும்.')
        : '';
      const text = lang === 'en'
        ? `Your overall attendance: ${currentStudent.overallAttendance}%\n\nSubject-wise:\n${subjectLines}${riskWarning}`
        : `உங்கள் ஒட்டுமொத்த வருகை: ${currentStudent.overallAttendance}%\n\nபாடவாரியாக:\n${subjectLines}${riskWarning}`;

      setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
      setInput('');
      return;
    }

    // Fees
    if (q.includes('fee') || q.includes('fees')) {
      const fee = getFeeRecord(currentStudent.id);
      const text = !fee
        ? (lang === 'en' ? 'No fee records found.' : 'கட்டண பதிவுகள் காணப்படவில்லை.')
        : (lang === 'en'
          ? `Fee Status: ${fee.status.toUpperCase()}\nTotal: ₹${fee.totalFee.toLocaleString()}\nPaid: ₹${fee.paidAmount.toLocaleString()}\nDue: ₹${(fee.totalFee - fee.paidAmount).toLocaleString()}\nDue Date: ${fee.dueDate}`
          : `கட்டண நிலை: ${fee.status === 'paid' ? 'செலுத்தப்பட்டது' : fee.status === 'pending' ? 'நிலுவையில்' : 'பகுதியாக'}\nமொத்தம்: ₹${fee.totalFee.toLocaleString()}\nசெலுத்தியது: ₹${fee.paidAmount.toLocaleString()}\nநிலுவை: ₹${(fee.totalFee - fee.paidAmount).toLocaleString()}`);

      setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
      setInput('');
      return;
    }

    // Exams
    if (q.includes('exam')) {
      const deptExams = getExamsForDepartment(currentStudent.department);
      const examLines = deptExams.slice(0, 4).map(e =>
        `  • ${e.subjectName} — ${e.date} at ${e.time} (${e.type})`
      ).join('\n');
      const text = deptExams.length === 0
        ? (lang === 'en' ? 'No upcoming exams found.' : 'வரவிருக்கும் தேர்வுகள் இல்லை.')
        : (lang === 'en' ? `Upcoming exams:\n${examLines}` : `வரவிருக்கும் தேர்வுகள்:\n${examLines}`);

      setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
      setInput('');
      return;
    }

    // CGPA
    if (q.includes('cgpa') || q.includes('gpa') || q.includes('grade')) {
      const text = lang === 'en'
        ? `Your current CGPA: ${currentStudent.cgpa}\nSemester-wise GPA: ${currentStudent.semesterGPA.join(', ')}`
        : `உங்கள் தற்போதைய CGPA: ${currentStudent.cgpa}\nசெமஸ்டர் வாரியாக GPA: ${currentStudent.semesterGPA.join(', ')}`;

      setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
      setInput('');
      return;
    }

    // Marks
    if (q.includes('mark') || q.includes('score')) {
      const marks = getMarks(currentStudent.id);
      const markLines = marks.map(m =>
        `  • ${m.subjectName}: IA1=${m.internal1}, IA2=${m.internal2}, IA3=${m.internal3} | Grade: ${m.grade || 'N/A'}`
      ).join('\n');
      const text = marks.length === 0
        ? (lang === 'en' ? 'No marks data found.' : 'மதிப்பெண் தரவு இல்லை.')
        : (lang === 'en' ? `Your marks:\n${markLines}` : `உங்கள் மதிப்பெண்கள்:\n${markLines}`);

      setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
      setInput('');
      return;
    }

    // Placement
    if (q.includes('placement') || q.includes('job') || q.includes('career')) {
      const text = lang === 'en'
        ? `Your placement readiness score: ${currentStudent.placementScore}%\nSkills: ${currentStudent.skills.join(', ')}\n\n${currentStudent.placementScore >= 70 ? 'You are well-prepared for placements!' : 'Consider improving your skills portfolio and CGPA to increase placement chances.'}`
        : `உங்கள் வேலைவாய்ப்பு தயார்நிலை மதிப்பெண்: ${currentStudent.placementScore}%\nதிறன்கள்: ${currentStudent.skills.join(', ')}`;

      setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
      setInput('');
      return;
    }

    // Default fallback
    const text = lang === 'en'
      ? 'I can help you with:\n• 🎒 Tomorrow\'s periods & bag packing checklist\n• 📊 Attendance & shortage alerts\n• 💳 Fee dues & receipts\n• 📝 Exams & internal marks\n• 💼 Placement readiness\n\nTry clicking one of the quick suggestions below!'
      : 'நான் உங்களுக்கு உதவக்கூடியவை:\n• 🎒 நாளைய வகுப்புகள் & எடுத்துச் செல்ல வேண்டியவை\n• 📊 வருகைப்பதிவு விவரங்கள்\n• 💳 கட்டண நிலுவை\n• 📝 தேர்வுகள் & மதிப்பெண்கள்\n• 💼 வேலைவாய்ப்பு தயார்நிலை';

    setMessages(prev => [...prev, userMsg, { id: botMsgId, role: 'bot', text }]);
    setInput('');
  }

  const analysisPreview = getAnalysis();

  return (
    <>
      {/* Floating proactive notification pill */}
      {!open && showPill && (
        <div className="fixed bottom-24 right-6 z-50 animate-count-up max-w-sm">
          <div className="bg-navy text-white p-3.5 rounded-2xl shadow-2xl border border-brass/30 flex items-start gap-3 relative backdrop-blur-md">
            <div className="w-8 h-8 rounded-full bg-brass/20 flex items-center justify-center shrink-0 text-brass mt-0.5">
              <Sparkles size={16} />
            </div>
            <div className="flex-1 pr-4 cursor-pointer" onClick={() => { setOpen(true); handleSendQuery("tomorrow's periods and checklist"); }}>
              <div className="flex items-center gap-1.5">
                <span className="text-[11px] font-bold uppercase tracking-wider text-brass">AI Schedule Reminder</span>
                <span className="w-1.5 h-1.5 rounded-full bg-safe animate-ping" />
              </div>
              <p className="text-xs font-semibold text-white mt-0.5">
                Tomorrow ({analysisPreview.targetDay}): {analysisPreview.slots.length} Classes
              </p>
              <p className="text-[11px] text-white/70 line-clamp-1">
                {analysisPreview.hasLab ? '🧪 Lab Coat & Observation Notebook needed!' : 'Tap to review your bag packing checklist'}
              </p>
            </div>
            <button
              onClick={(e) => { e.stopPropagation(); setShowPill(false); }}
              className="text-white/40 hover:text-white transition-colors"
            >
              <X size={14} />
            </button>
          </div>
        </div>
      )}

      {/* Floating Toggle button */}
      {!open && (
        <div className="fixed bottom-6 right-6 z-50">
          <button
            onClick={() => setOpen(true)}
            className="w-14 h-14 rounded-full shadow-xl flex items-center justify-center transition-transform hover:scale-105 active:scale-95 relative"
            style={{ background: 'linear-gradient(135deg, #16213E, #1F2E54)' }}
            title="Open AI Assistant"
          >
            <div className="w-10 h-10 rounded-full flex items-center justify-center bg-brass text-navy shadow-inner">
              <MessageCircle size={22} className="stroke-[2.5]" />
            </div>
            {/* Notification badge */}
            <span className="absolute -top-1 -right-1 w-5 h-5 bg-critical text-white text-[11px] font-bold rounded-full flex items-center justify-center border-2 border-white shadow">
              1
            </span>
          </button>
        </div>
      )}

      {/* Chat Window Panel */}
      {open && (
        <div
          className="fixed bottom-6 right-6 w-[420px] max-w-[calc(100vw-2rem)] bg-white rounded-2xl shadow-2xl z-50 flex flex-col border border-border animate-slide-in-right overflow-hidden"
          style={{ height: '580px', maxHeight: 'calc(100vh - 5rem)' }}
        >
          {/* Header */}
          <div className="px-5 py-3.5 border-b border-white/10 flex items-center justify-between text-white shrink-0"
               style={{ background: 'linear-gradient(135deg, #16213E, #1B294B)' }}>
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl flex items-center justify-center bg-gradient-to-br from-brass to-brass-dark text-navy font-bold shadow-md">
                <Sparkles size={18} />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="font-bold text-sm text-white">AI Study Assistant</h3>
                  <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-safe/20 text-emerald-300 border border-safe/30">
                    Online
                  </span>
                </div>
                <p className="text-white/50 text-xs">Bharath Institute ERP</p>
              </div>
            </div>

            <div className="flex items-center gap-1.5">
              <button
                onClick={() => setLang(lang === 'en' ? 'ta' : 'en')}
                className="flex items-center gap-1 px-2.5 py-1 rounded-lg text-xs font-medium text-white/80 hover:text-white bg-white/10 hover:bg-white/15 transition-all"
                title="Toggle English / தமிழ்"
              >
                <Globe size={13} />
                <span>{lang === 'en' ? 'EN' : 'தமிழ்'}</span>
              </button>
              <button
                onClick={() => setOpen(false)}
                className="p-1.5 rounded-lg text-white/60 hover:text-white hover:bg-white/10 transition-colors"
              >
                <X size={18} />
              </button>
            </div>
          </div>

          {/* Daily Alert Status Banner */}
          <div className="px-4 py-2 bg-brass/10 border-b border-brass/20 flex items-center justify-between text-xs text-navy shrink-0">
            <div className="flex items-center gap-2">
              <BellRing size={14} className="text-brass shrink-0" />
              <span className="font-medium">
                {lang === 'en' ? 'Daily 8:00 PM Timetable Reminder:' : 'தினசரி இரவு 8 மணி நினைவூட்டல்:'}
              </span>
            </div>
            <button
              onClick={() => setDailyAlert(!dailyAlert)}
              className={`px-2 py-0.5 rounded-full font-semibold text-[11px] transition-all flex items-center gap-1 ${
                dailyAlert
                  ? 'bg-safe text-white shadow-sm'
                  : 'bg-border text-text-secondary'
              }`}
            >
              {dailyAlert ? (lang === 'en' ? 'Active ✓' : 'செயலில் ✓') : (lang === 'en' ? 'Paused' : 'நிறுத்தப்பட்டது')}
            </button>
          </div>

          {/* Messages Area */}
          <div className="flex-1 overflow-y-auto px-4 py-4 space-y-3.5 bg-ivory/50">
            {messages.map((msg) => (
              <div key={msg.id} className="space-y-2">
                {/* Standard Message Bubble */}
                <div className={msg.role === 'user' ? 'chat-bubble-user' : 'chat-bubble-bot shadow-sm'}>
                  <p className="text-sm whitespace-pre-wrap leading-relaxed">{msg.text}</p>
                </div>

                {/* Rich Interactive Timetable Reminder Card */}
                {msg.type === 'timetable_reminder' && msg.analysis && (
                  <div className="bg-white rounded-xl border border-border shadow-md p-4 space-y-4 animate-count-up">
                    {/* Schedule Header */}
                    <div className="flex items-start justify-between border-b border-border/80 pb-3">
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-base">📅</span>
                          <h4 className="font-bold text-navy text-sm">
                            {lang === 'en' ? `${msg.analysis.targetDay}'s Schedule` : `${msg.analysis.targetDayTa} வகுப்பு அட்டவணை`}
                          </h4>
                        </div>
                        <p className="text-xs text-text-secondary mt-0.5 font-medium">{msg.analysis.dateStr}</p>
                      </div>

                      <div className="flex items-center gap-1.5 flex-wrap justify-end">
                        <span className="px-2 py-0.5 rounded-full text-[11px] font-semibold bg-navy text-white">
                          {msg.analysis.slots.length} {lang === 'en' ? 'Periods' : 'பீரியடுகள்'}
                        </span>
                        {msg.analysis.hasLab && (
                          <span className="px-2 py-0.5 rounded-full text-[11px] font-semibold bg-warn/15 text-warn border border-warn/30">
                            🧪 {lang === 'en' ? 'Lab Day' : 'செய்முறை'}
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Periods Accordion / Preview */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <p className="text-xs font-bold uppercase tracking-wider text-text-secondary">
                          {lang === 'en' ? 'Period Timeline' : 'வகுப்பு காலவரிசை'}
                        </p>
                        <button
                          onClick={() => setExpandedPeriods(p => ({ ...p, [msg.id]: !p[msg.id] }))}
                          className="text-xs text-brass hover:text-brass-dark flex items-center gap-0.5 font-semibold"
                        >
                          <span>{expandedPeriods[msg.id] ? (lang === 'en' ? 'Collapse' : 'சுருக்கு') : (lang === 'en' ? 'View All' : 'முழுவதும்')}</span>
                          {expandedPeriods[msg.id] ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
                        </button>
                      </div>

                      <div className="space-y-1.5">
                        {(expandedPeriods[msg.id] ? msg.analysis.slots : msg.analysis.slots.slice(0, 3)).map((slot, sIdx) => {
                          const isLab = slot.room.toLowerCase().includes('lab');
                          return (
                            <div
                              key={sIdx}
                              className={`p-2 rounded-lg text-xs flex items-center justify-between border ${
                                isLab ? 'bg-amber-50/60 border-amber-200' : 'bg-ivory border-border/60'
                              }`}
                            >
                              <div className="flex items-center gap-2 min-w-0">
                                <span className="font-bold text-navy w-6 tabular-nums">P{slot.period}</span>
                                <div className="truncate">
                                  <p className="font-semibold text-text-primary truncate">{slot.subjectName}</p>
                                  <p className="text-[11px] text-text-muted flex items-center gap-2">
                                    <span>{slot.faculty}</span>
                                  </p>
                                </div>
                              </div>
                              <div className="text-right shrink-0 pl-2">
                                <span className={`inline-flex items-center gap-1 font-medium px-1.5 py-0.5 rounded text-[10px] ${
                                  isLab ? 'bg-amber-200/60 text-amber-900 font-bold' : 'text-text-secondary bg-white'
                                }`}>
                                  <MapPin size={10} />
                                  {slot.room}
                                </span>
                                <p className="text-[10px] text-text-muted mt-0.5 tabular-nums">{slot.time.split('–')[0].trim()}</p>
                              </div>
                            </div>
                          );
                        })}
                        {!expandedPeriods[msg.id] && msg.analysis.slots.length > 3 && (
                          <p className="text-[11px] text-center text-text-muted italic pt-1">
                            +{msg.analysis.slots.length - 3} {lang === 'en' ? 'more periods (Click View All)' : 'கூடுதல் வகுப்புகள்'}
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Packing Checklist */}
                    <div className="border-t border-border/80 pt-3">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-1.5">
                          <span className="text-sm">🎒</span>
                          <span className="text-xs font-bold uppercase tracking-wider text-navy">
                            {lang === 'en' ? 'Smart Bag Packing Checklist' : 'எடுத்துச் செல்ல வேண்டிய பொருட்கள்'}
                          </span>
                        </div>
                        {/* Progress */}
                        {(() => {
                          const packedCount = msg.analysis.checklist.filter(c => c.packed).length;
                          const total = msg.analysis.checklist.length;
                          const pct = Math.round((packedCount / total) * 100);
                          return (
                            <span className="text-xs font-bold text-safe tabular-nums">
                              {packedCount}/{total} ({pct}%)
                            </span>
                          );
                        })()}
                      </div>

                      {/* Progress bar */}
                      {(() => {
                        const packedCount = msg.analysis.checklist.filter(c => c.packed).length;
                        const total = msg.analysis.checklist.length;
                        const pct = Math.round((packedCount / total) * 100);
                        return (
                          <div className="w-full h-1.5 bg-ivory-dark rounded-full overflow-hidden mb-3">
                            <div
                              className="h-full rounded-full transition-all duration-300"
                              style={{
                                width: `${pct}%`,
                                background: pct === 100 ? '#3D8B5A' : '#C89B3C',
                              }}
                            />
                          </div>
                        );
                      })()}

                      {/* Checklist Items */}
                      <div className="space-y-2">
                        {msg.analysis.checklist.map((item: ChecklistItem) => (
                          <div
                            key={item.id}
                            onClick={() => toggleItemPacked(msg.id, item.id)}
                            className={`p-2.5 rounded-lg border text-xs cursor-pointer select-none transition-all flex items-start gap-2.5 ${
                              item.packed
                                ? 'bg-emerald-50/60 border-emerald-200 text-text-secondary'
                                : 'bg-white border-border hover:border-brass/50 shadow-xs'
                            }`}
                          >
                            <button
                              type="button"
                              className="mt-0.5 text-navy hover:text-brass shrink-0 transition-colors"
                            >
                              {item.packed ? (
                                <CheckSquare size={16} className="text-safe" />
                              ) : (
                                <Square size={16} className="text-text-muted" />
                              )}
                            </button>

                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-1.5 flex-wrap">
                                <span className="text-sm">{item.icon}</span>
                                <span className={`font-semibold ${item.packed ? 'line-through text-text-muted' : 'text-navy'}`}>
                                  {lang === 'en' ? item.item : item.itemTa}
                                </span>
                                <span className={`text-[10px] px-1.5 py-0.2 rounded font-medium ${
                                  item.category === 'Mandatory'
                                    ? 'bg-critical/10 text-critical border border-critical/20'
                                    : item.category === 'Lab Kit'
                                    ? 'bg-amber-100 text-amber-900 border border-amber-300'
                                    : 'bg-ivory-dark text-text-secondary'
                                }`}>
                                  {item.category}
                                </span>
                              </div>
                              <p className="text-[11px] text-text-muted mt-0.5">
                                {lang === 'en' ? item.reason : item.reasonTa}
                              </p>
                            </div>
                          </div>
                        ))}
                      </div>

                      {/* 100% Packed Congratulations */}
                      {msg.analysis.checklist.every(c => c.packed) && (
                        <div className="mt-3 p-2.5 rounded-lg bg-emerald-50 border border-emerald-200 flex items-center gap-2 text-safe text-xs font-semibold animate-fade-in">
                          <Check size={16} />
                          <span>{lang === 'en' ? '🎉 Great job! Your bag is fully packed and ready for tomorrow.' : '🎉 அருமை! உங்கள் பை முழுமையாக தயார் செய்யப்பட்டுள்ளது.'}</span>
                        </div>
                      )}

                      {/* Card Action Buttons */}
                      <div className="flex items-center gap-2 mt-3 pt-2 border-t border-border/60">
                        <button
                          onClick={() => handleCopyChecklist(msg.id, msg.analysis!)}
                          className="flex-1 py-1.5 px-3 rounded-lg border border-border text-xs font-semibold text-navy hover:bg-ivory flex items-center justify-center gap-1.5 transition-colors"
                        >
                          {copiedId === msg.id ? (
                            <>
                              <Check size={13} className="text-safe" />
                              <span className="text-safe">{lang === 'en' ? 'Copied!' : 'நகலெடுக்கப்பட்டது!'}</span>
                            </>
                          ) : (
                            <>
                              <Copy size={13} />
                              <span>{lang === 'en' ? 'Copy Checklist' : 'பட்டியலை நகலெடு'}</span>
                            </>
                          )}
                        </button>

                        <button
                          onClick={() => setDailyAlert(prev => !prev)}
                          className={`py-1.5 px-3 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors ${
                            dailyAlert
                              ? 'bg-navy text-white hover:bg-navy-light'
                              : 'border border-border text-text-secondary hover:bg-ivory'
                          }`}
                        >
                          <Bell size={13} />
                          <span>{dailyAlert ? (lang === 'en' ? '8 PM Alert: ON' : 'அலர்ட்: ஆன்') : (lang === 'en' ? 'Set Reminder' : 'நினைவூட்டு')}</span>
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
            <div ref={messagesEnd} />
          </div>

          {/* Quick Suggestion Chips */}
          <div className="px-3 py-2 bg-white border-t border-border flex items-center gap-1.5 overflow-x-auto shrink-0 no-scrollbar">
            <button
              onClick={() => handleSendQuery("What are tomorrow's periods and checklist?")}
              className="px-2.5 py-1 rounded-full text-xs font-medium bg-brass/10 hover:bg-brass/20 text-navy border border-brass/30 shrink-0 flex items-center gap-1 transition-colors"
            >
              <span>🎒</span>
              <span>{lang === 'en' ? "Tomorrow's Checklist" : "நாளைய பட்டியல்"}</span>
            </button>

            <button
              onClick={() => handleSendQuery("Do I have any lab sessions tomorrow?")}
              className="px-2.5 py-1 rounded-full text-xs font-medium bg-ivory hover:bg-ivory-dark text-text-primary border border-border shrink-0 flex items-center gap-1 transition-colors"
            >
              <span>🧪</span>
              <span>{lang === 'en' ? "Lab Requirements" : "ஆய்வக தேவைகள்"}</span>
            </button>

            <button
              onClick={() => handleSendQuery("Check my overall attendance")}
              className="px-2.5 py-1 rounded-full text-xs font-medium bg-ivory hover:bg-ivory-dark text-text-primary border border-border shrink-0 flex items-center gap-1 transition-colors"
            >
              <span>📊</span>
              <span>{lang === 'en' ? "Attendance" : "வருகை"}</span>
            </button>

            <button
              onClick={() => handleSendQuery("Check fee payment status")}
              className="px-2.5 py-1 rounded-full text-xs font-medium bg-ivory hover:bg-ivory-dark text-text-primary border border-border shrink-0 flex items-center gap-1 transition-colors"
            >
              <span>💳</span>
              <span>{lang === 'en' ? "Fees" : "கட்டணம்"}</span>
            </button>
          </div>

          {/* Chat Input Bar */}
          <div className="p-3 bg-white border-t border-border shrink-0">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleSendQuery();
              }}
              className="flex gap-2"
            >
              <input
                value={input}
                onChange={e => setInput(e.target.value)}
                placeholder={lang === 'en' ? 'Ask: "Tomorrow periods", "What to bring?", "Attendance"...' : 'கேளுங்கள்: "நாளைய வகுப்புகள்", "எடுத்து வர வேண்டியவை"...'}
                className="flex-1 px-4 py-2.5 rounded-xl bg-ivory border border-border text-sm focus:outline-none focus:border-brass transition-colors"
              />
              <button
                type="submit"
                className="px-3.5 py-2.5 rounded-xl text-white transition-all hover:opacity-90 active:scale-95 shadow-sm"
                style={{ background: '#16213E' }}
                title="Send"
              >
                <Send size={16} />
              </button>
            </form>
          </div>
        </div>
      )}
    </>
  );
}
